name: Continuous Integration

on:
  push:
    paths-ignore:
      - "**/README.md"
  pull_request:
  workflow_dispatch:

env:
  CARGO_TERM_COLOR: always
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

jobs:
  rust-checks:
    name: Rust Checks
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        action:
          - command: build
            args: --release
          - command: fmt
            args: --all -- --check --color always
          - command: clippy
            # --all-targets is removed, see rust-lang/rust-analyzer#14205
            args: --all-features --workspace -- -D warnings
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Setup Rust
        uses: dtolnay/rust-toolchain@v1
        with:
          toolchain: nightly
          components: rust-src clippy rustfmt
      - name: Enable caching
        uses: Swatinem/rust-cache@v2
      - name: Run command
        working-directory: ./firmware/ascii-cosmo
        env:
          COSMO_WIFI_SSID: ssid
          COSMO_WIFI_PASSWORD: password
        run: |
          cargo install ldproxy
          cargo ${{ matrix.action.command }} ${{ matrix.action.args }}
